
---
# localhost profile
spring:
  profiles: local
  cloud:
      config:
        uri: http://localhost:8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
gateway:
  api:
    url: http://localhost:9001/
message: 'application.yml Config'


